In [ ]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [ ]:
b = torch.zeros(3)
b

tensor([0., 0., 0.])

In [ ]:
a[1]

tensor(1.)

In [ ]:
float(a[1])

1.0

In [ ]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [ ]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)
print(points.shape)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
torch.Size([3, 2])


In [ ]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [ ]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [ ]:
points[1:, 0]

tensor([5., 2.])

In [ ]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [ ]:
points = torch.tensor([[1.0, 4.0], [2.0, 5.0], [3.0, 6.0]])
print(points.size())
print(points.storage_offset())
print(points.stride())


torch.Size([3, 2])
0
(2, 1)


In [ ]:
points_gpu = points.to(device='cuda:01)

SyntaxError: ignored

In [ ]:
A = torch.tensor([1,2,3])
B = torch.tensor([3,4,5])
print(B-A)

tensor([2, 2, 2])


In [ ]:
torch.tensor([[1,2],[3,4]], device="cuda:0")

In [ ]:
torch.tensor([[1,2],[3,4]], device="cuda:0")